services:
  - type: web
    name: sk-store
    runtime: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_PUBLIC_KEY
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
      - key: DISCORD_ADMIN_ID
        sync: false
      - key: DISCORD_LOG_CHANNEL_ID
        sync: false
      - key: DISCORD_REDIRECT_URI
        sync: false
      - key: PIX_KEY
        sync: false
