import { useState } from "react";
import { Link } from "wouter";
import { ArrowLeft, Bot, Send, Sparkles, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";

type Message={role:"assistant"|"user";content:string};
const welcome="Fala! Eu sou o assistente da SK$. Posso conversar sobre sensibilidade do Free Fire, Free Fire MAX, celulares, FPS, HUD, botão de disparo e calibração. Me diga seu aparelho e o que você quer melhorar.";
export default function PremiumAI(){
 const [input,setInput]=useState(""); const [messages,setMessages]=useState<Message[]>([{role:"assistant",content:welcome}]); const [working,setWorking]=useState(false); const [message,setMessage]=useState("");
 const ask=async(text=input)=>{const question=text.trim();if(!question||working)return;setInput("");setMessage("");const transcript=[...messages,{role:"user",content:question}].slice(-8).map(m=>`${m.role}: ${m.content}`).join("\n");setMessages(m=>[...m,{role:"user",content:question}]);setWorking(true);try{const response=await fetch("/api/premium-ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({device:/^(ola|olá|oi|oie|e ai|e aí|bom dia|boa tarde|boa noite)[!,.?\\s]*$/i.test(question)?question:transcript,refreshRate:"informado na conversa",style:"conversa",game:/emulador|pc|mouse|dpi/i.test(question)?"Free Fire emulador":"Free Fire / Free Fire MAX"})});const body=await response.json();if(!response.ok)throw new Error(body.error||"Não foi possível responder agora.");setMessages(m=>[...m,{role:"assistant",content:body.recommendation}]);}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível responder agora.");}finally{setWorking(false)}};
 return <div className="checkout-page ai-page chat-page"><header className="checkout-header"><Link href="/" className="brand"><span className="brand-mark">SK$</span><span>STORE</span></Link><Link href="/" className="back-link"><ArrowLeft size={16}/> Voltar para a loja</Link></header><main className="checkout-main"><span className="section-index"><Sparkles size={14}/> PREMIUM AI · CHAT</span><h1>Converse com seu setup.</h1><p className="checkout-intro">Um chat focado em Free Fire, sensibilidade e celulares. As sugestões são legais, ajustáveis e explicadas passo a passo.</p><div className="chat-shell"><aside className="chat-sidebar"><div className="bot-avatar"><Bot size={24}/></div><h2>SK$ Coach</h2><p>Assistente especializado</p><div className="scope-list"><span>✦ Free Fire / MAX</span><span>✦ Android e iPhone</span><span>✦ HUD, FPS e calibração</span></div><small>O chat não orienta macros, scripts, exploits ou alterações de arquivos.</small></aside><section className="chat-panel"><div className="chat-top"><span><i className="online-dot"/> SK$ Coach</span><small>ONLINE · PREMIUM</small></div><div className="chat-messages">{messages.map((m,i)=><div className={`chat-message ${m.role}`} key={i}><div className="message-icon">{m.role==="assistant"?<Bot size={15}/>:<UserRound size={15}/>}</div><div><small>{m.role==="assistant"?"SK$ Coach":"Você"}</small><p>{m.content}</p></div></div>)}{working&&<div className="chat-message assistant"><div className="message-icon"><Bot size={15}/></div><div className="typing"><b/><b/><b/></div></div>}</div><div className="suggestions"><button onClick={()=>ask("Meu aparelho é um Galaxy A54. Qual sensibilidade inicial para Free Fire MAX?")}>Galaxy A54 + MAX</button><button onClick={()=>ask("Como calibrar o botão de disparo no iPhone?")}>Calibrar iPhone</button><button onClick={()=>ask("Como melhorar controle sem passar do alvo?")}>Mais controle</button></div><form className="chat-input" onSubmit={e=>{e.preventDefault();ask()}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Pergunte sobre sua sensi..." aria-label="Mensagem"/><Button type="submit" disabled={working||!input.trim()}><Send size={16}/><span>Enviar</span></Button></form>{message&&<p className="checkout-feedback">{message}</p>}</section></div></main></div>;
}


