export type ProductCategory = "sensi" | "emulator" | "ai" | "software";
export type DeviceProfile = { model:string; platform:"android"|"ios"|"emulator"; sensitivity:{general:number; redDot:number; scope2x:number; scope4x:number}; dpi?:number; tutorial:string[] };
export type CatalogProduct = { id:string; slug:string; name:string; category:ProductCategory; shortDescription:string; description:string; priceCents:number; status:"available"|"coming_soon"; tags:string[]; compatibility:string[]; included:string[]; updatedAt:string; requirements?:string[]; faq?:{question:string;answer:string}[]; deviceProfiles?:DeviceProfile[] };
export const PRODUCT_DETAILS: Record<string,{requirements:string[]; faq:{question:string;answer:string}[]}> = {
  "sensi-normal": {requirements:["Free Fire ou Free Fire MAX atualizado","Android 9+ ou iOS 15+","Acesso ao campo de treinamento"],faq:[{question:"A sensibilidade serve para qualquer aparelho?",answer:"Escolha o modelo mais próximo na página do pack e aplique os passos do tutorial."}]},
  "sensi-premium": {requirements:["Free Fire ou Free Fire MAX atualizado","Conta Discord autenticada","Conexão com a internet para usar o SK$ Coach"],faq:[{question:"Como funciona a IA?",answer:"O SK$ Coach analisa seu aparelho, estilo e feedback do treino para sugerir ajustes."}]},
  "sensi-emulator": {requirements:["Windows 10 ou superior","BlueStacks 5 ou LDPlayer 9","Mouse configurado e FPS estável"],faq:[{question:"Posso usar no celular?",answer:"Este pack é exclusivo para emuladores no PC; use os packs de celular para Android ou iPhone."}]}
};
export const CATALOG: CatalogProduct[] = [
 {id:"sensi-normal",slug:"sensi-normal",name:"Pack Sensi Normal",category:"sensi",shortDescription:"Perfis por aparelho para Free Fire e Free Fire MAX.",description:"Presets organizados para Android e iPhone, com guia de aplicação e ajustes por modelo.",priceCents:1990,status:"available",tags:["Android","iPhone","Free Fire MAX"],compatibility:["Android 9+","iOS 15+"],included:["Perfis por modelo","Guia de aplicação","Acesso protegido"],updatedAt:"2026-09-14",deviceProfiles:[{model:"Samsung Galaxy A54",platform:"android",sensitivity:{general:178,redDot:164,scope2x:152,scope4x:138},dpi:411,tutorial:["Ative 120 Hz","Use DPI 411 e toque padrão","Treine arrasto curto por 5 minutos"]},{model:"Xiaomi Redmi Note 12",platform:"android",sensitivity:{general:185,redDot:172,scope2x:158,scope4x:142},dpi:440,tutorial:["Ative 120 Hz","Use DPI 440","Mantenha aceleração do sistema desligada"]},{model:"Motorola Moto G84",platform:"android",sensitivity:{general:180,redDot:168,scope2x:154,scope4x:140},dpi:420,tutorial:["Ative taxa de atualização alta","Comece com botão de disparo 48%","Ajuste em passos de 5 no treinamento"]},{model:"iPhone 13",platform:"ios",sensitivity:{general:160,redDot:150,scope2x:140,scope4x:125},tutorial:["Ative resposta ao toque padrão","Desative zoom da tela","Ajuste o botão de disparo antes do treino"]},{model:"iPhone 8",platform:"ios",sensitivity:{general:150,redDot:142,scope2x:130,scope4x:115},tutorial:["Use escala de tela padrão","Ative resposta tátil","Faça o primeiro ajuste em campo de treino"]}]},
 {id:"sensi-premium",slug:"sensi-premium",name:"Pack Sensi Premium",category:"ai",shortDescription:"Perfis detalhados e assistente IA especializado.",description:"Configurações por dispositivo, tutorial completo e acesso ao SK$ Coach para ajustes personalizados.",priceCents:3990,status:"available",tags:["IA Premium","Android","iPhone"],compatibility:["Android 9+","iOS 15+"],included:["Perfis por modelo","SK$ Coach","Guias protegidos"],updatedAt:"2026-09-14",deviceProfiles:[{model:"Samsung Galaxy A54 · competitivo",platform:"android",sensitivity:{general:185,redDot:172,scope2x:160,scope4x:145},dpi:411,tutorial:["Use 120 Hz e DPI 411","Teste arrasto em diagonal","Peça ao SK$ Coach um ajuste fino com seu FPS"]},{model:"iPhone 13 · competitivo",platform:"ios",sensitivity:{general:170,redDot:158,scope2x:146,scope4x:130},tutorial:["Mantenha escala padrão","Ajuste toque tátil para firme","Use o chat para polir a sensi após o treino"]}]},
 {id:"sensi-emulator",slug:"sensi-emulator",name:"Pack Sensi Emulador",category:"emulator",shortDescription:"Presets para mouse, DPI, resolução e FPS no PC.",description:"Configurações separadas para emuladores, com tutorial de sensibilidade e controles.",priceCents:2990,status:"available",tags:["PC","Mouse","DPI"],compatibility:["Windows 10+","Emuladores Android"],included:["Perfis de emulador","Guia de DPI","Acesso protegido"],updatedAt:"2026-09-14",deviceProfiles:[{model:"BlueStacks 5 · 1920×1080",platform:"emulator",sensitivity:{general:150,redDot:135,scope2x:120,scope4x:105},dpi:800,tutorial:["Use mouse 800 DPI","Trave FPS em 120","Comece com sensibilidade horizontal 1.0 e ajuste em passos de 5"]},{model:"LDPlayer 9 · 1600×900",platform:"emulator",sensitivity:{general:145,redDot:130,scope2x:115,scope4x:100},dpi:800,tutorial:["Ative alta taxa de quadros","Mantenha aceleração do mouse desligada","Calibre o arrasto no campo de treino"]}]}
];
export function getProduct(slug:string){return CATALOG.find(product=>product.slug===slug);}
