export type ProductCategory = "sensi" | "emulator" | "ai" | "software";
export type CatalogProduct = { id:string; slug:string; name:string; category:ProductCategory; shortDescription:string; description:string; priceCents:number; status:"available"|"coming_soon"; tags:string[]; compatibility:string[]; included:string[]; updatedAt:string; requirements?:string[]; faq?:{question:string;answer:string}[] };
export const PRODUCT_DETAILS: Record<string,{requirements:string[]; faq:{question:string;answer:string}[]}> = {
  "sensi-normal": {requirements:["Free Fire ou Free Fire MAX atualizado","Android 9+ ou iOS 15+","Acesso ao campo de treinamento"],faq:[{question:"A sensibilidade serve para qualquer aparelho?",answer:"Escolha o modelo mais próximo na página do pack e aplique os passos do tutorial."}]},
  "sensi-premium": {requirements:["Free Fire ou Free Fire MAX atualizado","Conta Discord autenticada","Conexão com a internet para usar o SK$ Coach"],faq:[{question:"Como funciona a IA?",answer:"O SK$ Coach analisa seu aparelho, estilo e feedback do treino para sugerir ajustes."}]},
  "sensi-emulator": {requirements:["Windows 10 ou superior","BlueStacks 5 ou LDPlayer 9","Mouse configurado e FPS estável"],faq:[{question:"Posso usar no celular?",answer:"Este pack é exclusivo para emuladores no PC; use os packs de celular para Android ou iPhone."}]}
};
export const CATALOG: CatalogProduct[] = [
 {id:"sensi-normal",slug:"sensi-normal",name:"Pack Sensi Normal",category:"sensi",shortDescription:"Perfis por aparelho para Free Fire e Free Fire MAX.",description:"Presets organizados para Android e iPhone, com guia de aplicação e ajustes por modelo.",priceCents:1990,status:"available",tags:["Android","iPhone","Free Fire MAX"],compatibility:["Android 9+","iOS 15+"],included:["Perfis por modelo","Guia de aplicação","Acesso protegido"],updatedAt:"2026-09-14"},
 {id:"sensi-premium",slug:"sensi-premium",name:"Pack Sensi Premium",category:"ai",shortDescription:"Perfis detalhados e assistente IA especializado.",description:"Configurações por dispositivo, tutorial completo e acesso ao SK$ Coach para ajustes personalizados.",priceCents:3990,status:"available",tags:["IA Premium","Android","iPhone"],compatibility:["Android 9+","iOS 15+"],included:["Perfis por modelo","SK$ Coach","Guias protegidos"],updatedAt:"2026-09-14"},
 {id:"sensi-emulator",slug:"sensi-emulator",name:"Pack Sensi Emulador",category:"emulator",shortDescription:"Presets para mouse, DPI, resolução e FPS no PC.",description:"Configurações separadas para emuladores, com tutorial de sensibilidade e controles.",priceCents:2990,status:"available",tags:["PC","Mouse","DPI"],compatibility:["Windows 10+","Emuladores Android"],included:["Perfis de emulador","Guia de DPI","Acesso protegido"],updatedAt:"2026-09-14"}
];
export function getProduct(slug:string){return CATALOG.find(product=>product.slug===slug);}
