export type ProductCategory = "sensi" | "emulator" | "ai" | "software";
export type DeviceProfile = { model:string; platform:"android"|"ios"|"emulator"; sensitivity:{general:number; redDot:number; scope2x:number; scope4x:number}; dpi?:number; tutorial:string[] };
export type CatalogProduct = { id:string; slug:string; name:string; category:ProductCategory; shortDescription:string; description:string; priceCents:number; status:"available"|"coming_soon"; tags:string[]; compatibility:string[]; included:string[]; updatedAt:string; deviceProfiles?:DeviceProfile[] };
export const CATALOG: CatalogProduct[] = [
 {id:"sensi-normal",slug:"sensi-normal",name:"Pack Sensi Normal",category:"sensi",shortDescription:"Perfis por aparelho para Free Fire e Free Fire MAX.",description:"Presets organizados para Android e iPhone, com guia de aplicação e ajustes por modelo.",priceCents:1990,status:"available",tags:["Android","iPhone","Free Fire MAX"],compatibility:["Android 9+","iOS 15+"],included:["Perfis por modelo","Guia de aplicação","Acesso protegido"],updatedAt:"2026-09-14",deviceProfiles:[{model:"Samsung Galaxy A54",platform:"android",sensitivity:{general:178,redDot:164,scope2x:152,scope4x:138},dpi:411,tutorial:["Ative 120 Hz","Use DPI 411 e toque padrão","Treine arrasto curto por 5 minutos"]},{model:"iPhone 13",platform:"ios",sensitivity:{general:160,redDot:150,scope2x:140,scope4x:125},tutorial:["Ative resposta ao toque padrão","Desative zoom da tela","Ajuste o botão de disparo antes do treino"]}]},
 {id:"sensi-premium",slug:"sensi-premium",name:"Pack Sensi Premium",category:"ai",shortDescription:"Perfis detalhados e assistente IA especializado.",description:"Configurações por dispositivo, tutorial completo e acesso ao SK$ Coach para ajustes personalizados.",priceCents:3990,status:"available",tags:["IA Premium","Android","iPhone"],compatibility:["Android 9+","iOS 15+"],included:["Perfis por modelo","SK$ Coach","Guias protegidos"],updatedAt:"2026-09-14"},
 {id:"sensi-emulator",slug:"sensi-emulator",name:"Pack Sensi Emulador",category:"emulator",shortDescription:"Presets para mouse, DPI, resolução e FPS no PC.",description:"Configurações separadas para emuladores, com tutorial de sensibilidade e controles.",priceCents:2990,status:"available",tags:["PC","Mouse","DPI"],compatibility:["Windows 10+","Emuladores Android"],included:["Perfis de emulador","Guia de DPI","Acesso protegido"],updatedAt:"2026-09-14",deviceProfiles:[{model:"BlueStacks 5 · 1920×1080",platform:"emulator",sensitivity:{general:150,redDot:135,scope2x:120,scope4x:105},dpi:800,tutorial:["Use mouse 800 DPI","Trave FPS em 120","Comece com sensibilidade horizontal 1.0 e ajuste em passos de 5"]},{model:"LDPlayer 9 · 1600×900",platform:"emulator",sensitivity:{general:145,redDot:130,scope2x:115,scope4x:100},dpi:800,tutorial:["Ative alta taxa de quadros","Mantenha aceleração do mouse desligada","Calibre o arrasto no campo de treino"]}]}
];
export function getProduct(slug:string){return CATALOG.find(product=>product.slug===slug);}
