export const DEVICES: Record<string, string[]> = {
  "Apple": [
    "iPhone 6s",
    "iPhone 6s Plus",
    "iPhone SE (1ª geração)",
    "iPhone 7",
    "iPhone 7 Plus",
    "iPhone 8",
    "iPhone 8 Plus",
    "iPhone X",
    "iPhone XR",
    "iPhone XS",
    "iPhone XS Max",
    "iPhone SE (2ª geração)",
    "iPhone SE (3ª geração)",
    "iPhone 11",
    "iPhone 11 Pro",
    "iPhone 11 Pro Max",
    "iPhone 12",
    "iPhone 12 Pro",
    "iPhone 12 Pro Max",
    "iPhone 13",
    "iPhone 13 Pro",
    "iPhone 13 Pro Max",
    "iPhone 14",
    "iPhone 14 Pro",
    "iPhone 14 Pro Max",
    "iPhone 15",
    "iPhone 15 Pro",
    "iPhone 15 Pro Max",
    "iPhone 16",
    "iPhone 16 Pro",
    "iPhone 16 Pro Max",
    "iPhone 17",
    "iPhone 17 Pro",
    "iPhone 17 Pro Max",
    "iPhone 12 mini",
    "iPhone 13 mini",
    "iPhone 14 Plus",
    "iPhone 15 Plus",
    "iPhone 16 Plus",
    "iPhone 16e",
    "iPhone 17e",
    "iPhone Air",
    "iPhone 18 Pro",
    "iPhone 18 Pro Max",
    "iPhone Duo"
  ],
  "Samsung": [
    "Galaxy A03",
    "Galaxy A04",
    "Galaxy A05",
    "Galaxy A06",
    "Galaxy A10",
    "Galaxy A12",
    "Galaxy A13",
    "Galaxy A14",
    "Galaxy A15",
    "Galaxy A16",
    "Galaxy A20",
    "Galaxy A21s",
    "Galaxy A22",
    "Galaxy A23",
    "Galaxy A24",
    "Galaxy A25",
    "Galaxy A26",
    "Galaxy A30",
    "Galaxy A31",
    "Galaxy A32",
    "Galaxy A33",
    "Galaxy A34",
    "Galaxy A35",
    "Galaxy A36",
    "Galaxy A50",
    "Galaxy A51",
    "Galaxy A52",
    "Galaxy A53",
    "Galaxy A54",
    "Galaxy A55",
    "Galaxy A56",
    "Galaxy M12",
    "Galaxy M14",
    "Galaxy M15",
    "Galaxy M23",
    "Galaxy M31",
    "Galaxy M32",
    "Galaxy M34",
    "Galaxy M35",
    "Galaxy S10",
    "Galaxy S20",
    "Galaxy S20 FE",
    "Galaxy S21",
    "Galaxy S21 FE",
    "Galaxy S22",
    "Galaxy S23",
    "Galaxy S23 FE",
    "Galaxy S24",
    "Galaxy S24 FE",
    "Galaxy S25",
    "Galaxy S25 Ultra"
  ],
  "Xiaomi": [
    "Mi 9",
    "Mi 10",
    "Mi 11",
    "Xiaomi 12",
    "Xiaomi 12 Lite",
    "Xiaomi 13",
    "Xiaomi 13T",
    "Xiaomi 14",
    "Xiaomi 14T",
    "Xiaomi 15"
  ],
  "Redmi": [
    "Redmi 9",
    "Redmi 9A",
    "Redmi 9C",
    "Redmi 10",
    "Redmi 10A",
    "Redmi 10C",
    "Redmi 12",
    "Redmi 12C",
    "Redmi 13",
    "Redmi 13C",
    "Redmi 14C",
    "Redmi Note 8",
    "Redmi Note 9",
    "Redmi Note 10",
    "Redmi Note 10 Pro",
    "Redmi Note 11",
    "Redmi Note 11 Pro",
    "Redmi Note 12",
    "Redmi Note 12 Pro",
    "Redmi Note 13",
    "Redmi Note 13 Pro",
    "Redmi Note 13 Pro+",
    "Redmi Note 14",
    "Redmi Note 14 Pro"
  ],
  "POCO": [
    "POCO M3",
    "POCO M4 Pro",
    "POCO M5",
    "POCO M6 Pro",
    "POCO X3 NFC",
    "POCO X3 Pro",
    "POCO X4 Pro",
    "POCO X5",
    "POCO X5 Pro",
    "POCO X6",
    "POCO X6 Pro",
    "POCO X7",
    "POCO X7 Pro",
    "POCO F3",
    "POCO F4",
    "POCO F5",
    "POCO F6",
    "POCO F7"
  ],
  "Motorola": [
    "Moto G7",
    "Moto G8",
    "Moto G9 Play",
    "Moto G10",
    "Moto G20",
    "Moto G22",
    "Moto G23",
    "Moto G24",
    "Moto G30",
    "Moto G31",
    "Moto G32",
    "Moto G34",
    "Moto G35",
    "Moto G40",
    "Moto G50",
    "Moto G52",
    "Moto G53",
    "Moto G54",
    "Moto G55",
    "Moto G60",
    "Moto G71",
    "Moto G72",
    "Moto G73",
    "Moto G75",
    "Moto G82",
    "Moto G84",
    "Moto G85",
    "Moto E7",
    "Moto E13",
    "Moto E14",
    "Edge 20",
    "Edge 30",
    "Edge 40",
    "Edge 50",
    "Edge 50 Pro"
  ],
  "LG": [
    "K40s",
    "K41s",
    "K50s",
    "K51s",
    "K61",
    "K62",
    "K62+",
    "K71",
    "G7 ThinQ",
    "G8s ThinQ",
    "V50 ThinQ",
    "Velvet"
  ],
  "Realme": [
    "C35",
    "C53",
    "C55",
    "C61",
    "C67",
    "Realme 9",
    "Realme 10",
    "Realme 11",
    "Realme 12",
    "Realme 13",
    "GT Neo 3",
    "GT 6"
  ],
  "ASUS": [
    "Zenfone 8",
    "Zenfone 9",
    "Zenfone 10",
    "ROG Phone 5",
    "ROG Phone 6",
    "ROG Phone 7",
    "ROG Phone 8"
  ],
  "Outra marca": []
};
export type DeviceProfile = { brand: string; model: string; game: string; style: string };
export function validDeviceProfile(v: any): v is DeviceProfile { return v && Object.hasOwn(DEVICES,v.brand) && typeof v.model === "string" && v.model.trim().length >= 2 && v.model.length <= 100 && ["Free Fire", "Free Fire MAX"].includes(v.game) && ["Equilibrado", "Mais controle", "Movimentos rápidos"].includes(v.style); }
